version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
        environment:
          CHROME_BIN: /usr/bin/google-chrome
    working_directory: ~/react-form

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - react-form-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: react-form-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run ci_test
